=== strimelle/marshalling/src/main/resources/XML/dtd-schema.dtd
<!ELEMENT students (student)*>
        <!ELEMENT student (id,first-name,last-name,courses)?>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT first-name (#PCDATA)>
        <!ELEMENT last-name (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT gpa (#PCDATA)>
        <!ELEMENT courses (course)*>
        <!ELEMENT course (name)*>
        <!ELEMENT name (#PCDATA)>

=== strimelle/marshalling/src/main/resources/XML/students.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE students SYSTEM "dtd-schema.dtd">-->
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="xsd-schema.xsd">
    <student>
        <id>001</id>
        <first-name>Emma</first-name>
        <last-name>Johansson</last-name>
        <courses>
            <course><name>Introduction to Programming</name></course>
            <course><name>Data Structures and Algorithms</name></course>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Database Systems</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Statistics and Probability</name></course>
        </courses>
    </student>
    <student>
        <id>002</id>
        <first-name>Lucas</first-name>
        <last-name>Martinez</last-name>
        <courses>
            <course><name>Data Structures and Algorithms</name></course>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Database Systems</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Statistics and Probability</name></course>
            <course><name>Software Engineering Principles</name></course>
        </courses>
    </student>
    <student>
        <id>003</id>
        <first-name>Olivia</first-name>
        <last-name>Chen</last-name>
        <courses>
            <course><name>Introduction to Programming</name></course>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Database Systems</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Software Testing and Quality Assurance</name></course>
            <course><name>Cloud Computing</name></course>
        </courses>
    </student>
    <student>
        <id>004</id>
        <first-name>Noah</first-name>
        <last-name>Kowalski</last-name>
        <courses>
            <course><name>Data Structures and Algorithms</name></course>
            <course><name>Database Systems</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Statistics and Probability</name></course>
            <course><name>Software Engineering Principles</name></course>
            <course><name>Cloud Computing</name></course>
            <course><name>Cybersecurity Fundamentals</name></course>
        </courses>
    </student>
    <student>
        <id>005</id>
        <first-name>Sophia</first-name>
        <last-name>Nguyen</last-name>
        <courses>
            <course><name>Introduction to Programming</name></course>
            <course><name>Data Structures and Algorithms</name></course>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Statistics and Probability</name></course>
            <course><name>Software Engineering Principles</name></course>
            <course><name>Technical Communication</name></course>
        </courses>
    </student>
    <student>
        <id>006</id>
        <first-name>Ethan</first-name>
        <last-name>OBrien</last-name>
        <courses>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Database Systems</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Statistics and Probability</name></course>
            <course><name>Software Testing and Quality Assurance</name></course>
            <course><name>Cloud Computing</name></course>
            <course><name>Cybersecurity Fundamentals</name></course>
        </courses>
    </student>
    <student>
        <id>007</id>
        <first-name>Ava</first-name>
        <last-name>Petrov</last-name>
        <courses>
            <course><name>Introduction to Programming</name></course>
            <course><name>Data Structures and Algorithms</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Software Engineering Principles</name></course>
            <course><name>Software Testing and Quality Assurance</name></course>
            <course><name>Cloud Computing</name></course>
            <course><name>Technical Communication</name></course>
        </courses>
    </student>
    <student>
        <id>008</id>
        <first-name>Mason</first-name>
        <last-name>Dubois</last-name>
        <courses>
            <course><name>Data Structures and Algorithms</name></course>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Database Systems</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Statistics and Probability</name></course>
            <course><name>Software Testing and Quality Assurance</name></course>
            <course><name>Cybersecurity Fundamentals</name></course>
            <course><name>Technical Communication</name></course>
        </courses>
    </student>
    <student>
        <id>009</id>
        <first-name>Isabella</first-name>
        <last-name>Rossi</last-name>
        <courses>
            <course><name>Introduction to Programming</name></course>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Database Systems</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Statistics and Probability</name></course>
            <course><name>Software Engineering Principles</name></course>
            <course><name>Cloud Computing</name></course>
            <course><name>Technical Communication</name></course>
        </courses>
    </student>
    <student>
        <id>010</id>
        <first-name>Liam</first-name>
        <last-name>Anderson</last-name>
        <courses>
            <course><name>Data Structures and Algorithms</name></course>
            <course><name>Object-Oriented Programming</name></course>
            <course><name>Web Services and Distributed Systems</name></course>
            <course><name>Computer Networks</name></course>
            <course><name>Operating Systems</name></course>
            <course><name>Calculus I</name></course>
            <course><name>Discrete Mathematics</name></course>
            <course><name>Software Engineering Principles</name></course>
            <course><name>Cybersecurity Fundamentals</name></course>
            <course><name>Technical Communication</name></course>
        </courses>
    </student>
</students>
